[server]
enableStaticServing = true

[theme]
base = "light" 
primaryColor = "#FF4B4B"          # Rosso (Bottoni, Slider, Accenti)
 # Grigio Antracite (Sidebar e Widget)
textColor = "#000000"             # Bianco (Testo)
font = "sans serif"
